`try()` to generate `output.ses_smtp_password_v4`
In module upgrades, I'm seeing errors like this:

    Error: Invalid function argument

    on .terraform/modules/user/outputs.tf line 29, in output "ses_smtp_password_v4":
    29:   value       = join("", aws_iam_access_key.default.*.ses_smtp_password_v4)
        |----------------
        | aws_iam_access_key.default is tuple with 1 element

    Invalid value for "lists" parameter: element 0 is null; cannot concatenate
    null values.

This change wraps the `join()` with a `try(..., null)`, causing `null`
to be returned as a fallback on error.